print('Tabuada v1.0')
nt = int(input('Digite um número e veja sua tabuada: '))
print('Tabuada do {}'.format(nt))
print('='*12)
print('{} x {:2} = {}'.format(nt, 1, 1 * nt))
print('{} x {:2} = {}'.format(nt, 2, 2 * nt))
print('{} x {:2} = {}'.format(nt, 3, 3 * nt))
print('{} x {:2} = {}'.format(nt, 4, 4 * nt))
print('{} x {:2} = {}'.format(nt, 5, 5 * nt))
print('{} x {:2} = {}'.format(nt, 6, 6 * nt))
print('{} x {:2} = {}'.format(nt, 7, 7 * nt))
print('{} x {:2} = {}'.format(nt, 8, 8 * nt))
print('{} x {:2} = {}'.format(nt, 9, 9 * nt))
print('{} x {:2} = {}'.format(nt, 10, 10 * nt))
print('='*12)
