n = input('Digite aluguma coisa:')
print('A classe primitiva desse valor é {}'.format(type(n)))
print('É um número? {}'.format(n.isnumeric()))
print('É alfabético (letra)? {}'.format(n.isalpha()))
print('É alfanumérico (letra e número)? {}'.format(n.isalnum()))
print('Está em maiúsculas? {}'.format(n.isupper()))
print('Está em minúsculas? {}'.format(n.islower()))
print('Só tem espaços? {}'.format(n.isspace()))
print('Está captalizado? {}'.format(n.istitle()))
