print('Analisador de textos')
nome = str(input('Digite seu nome completo: ')).strip()
print('Seu nome em letras maiúsculas é {}'.format(nome.lower()))
print('Seu nome em letras minúsculas é {}'.format(nome.upper()))
print('Seu nome tem {} letras ao todo'.format(len(nome) - nome.count(' ')))
pn = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(pn[0], len(pn[0])))
